### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by currentoor** [Jannis/om-next-kanban-demo#2]
What are the `resources/app.cljs.edn` and `resources/cards.cljs.edn` files for and how are they being used?

Awesome job by the way!

**Comment by Jannis** [comment]
`app.cljs.edn` and `cards.cljs.edn` are the files that `boot-cljs` uses to generate `app.js` and `cards.js`. See https://github.com/adzerk-oss/boot-cljs/wiki/Usage for more information.
